#!/usr/bin/env python

import os
import sys
import utils
from .. import CASIO
from .utils.path_config import get_nsys_gpukernsum_file

all_kerns = set()


for app in utils.apps:
    prettyname = utils.app_pretty_names[app].replace('_', '\\_')

    for plat in utils.plats:
        for config in utils.app_configs[app]:
            if not os.path.exists(get_nsys_gpukernsum_file(plat, app, config)): continue

            cuda_kerns = set()
            with open(get_nsys_gpukernsum_file(plat, app, config)) as f:
                next(f)
                for line in f:
                    if not utils.is_blacklisted(line):
                        _, _2, result = utils.parse_nsys_kernsum(line.strip())
                        cuda_kerns.add(result)

            all_kerns = all_kerns.union(cuda_kerns)

for k in all_kerns:
    print(k)


